services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - MONGO_URL=${MONGO_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - LOG_LEVEL=INFO
      - JSON_LOGS=True
    restart: always
    shm_size: '1gb'

  worker:
    build: .
    command: arq backend.app.workers.tasks.WorkerSettings
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - MONGO_URL=${MONGO_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - LOG_LEVEL=INFO
      - JSON_LOGS=True
    volumes:
      - ./profiles:/app/.profiles
    restart: always
    shm_size: '1gb'

volumes:
  mongodb_data:
